"""
Pydantic schemas for the task planner.

Hierarchy
─────────
  PlanStep          – a single tool call in a plan
  ExecutionPlan     – the full ordered plan for one user command
  StepResult        – outcome of executing one step
  PlanExecutionResponse – top-level response returned to the frontend
"""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field


# ─── Step status lifecycle ────────────────────────────────────────────────────

StepStatus = Literal["pending", "running", "completed", "failed", "approval_required", "skipped"]


# ─── Plan building blocks ─────────────────────────────────────────────────────

class PlanStep(BaseModel):
    """One step in an execution plan."""

    index: int
    """Zero-based position in the plan."""

    tool: str
    """Tool registry name (e.g. 'sort_downloads', 'summarize_document')."""

    description: str
    """Human-readable label shown in the UI step list."""

    args: Dict[str, Any] = Field(default_factory=dict)
    """Arguments forwarded to the tool's run() method."""

    requires_approval: bool = False
    """Mirrors the tool's requires_approval flag so the planner can pre-flag it."""

    status: StepStatus = "pending"
    """Lifecycle state – mutated by the executor as the plan runs."""


class ExecutionPlan(BaseModel):
    """
    Ordered list of steps that together fulfil a user goal.

    Generated by task_planner.plan_command() and consumed by
    plan_executor.execute_plan().
    """

    goal: str
    """The original user command / intent description."""

    steps: List[PlanStep]

    is_multi_step: bool = True
    """False for single-step plans that are just passing through the planner."""


# ─── Execution results ────────────────────────────────────────────────────────

class StepResult(BaseModel):
    """Result of executing a single plan step."""

    step_index: int
    tool: str
    status: StepStatus
    message: Optional[str] = None
    data: Optional[Any] = None
    approval_id: Optional[int] = None
    """Set when the step was paused waiting for approval."""


class PlanExecutionResponse(BaseModel):
    """
    Top-level response envelope for a planned command execution.

    Mirrors CommandResponse but carries per-step results instead of
    a single ToolResult.
    """

    command: str
    """The original user command."""

    plan: ExecutionPlan
    """The plan that was (or is being) executed."""

    step_results: List[StepResult] = Field(default_factory=list)
    """Results for each completed / paused step."""

    overall_status: StepStatus = "pending"
    """
    Aggregate status:
    - 'completed'          – all steps finished successfully
    - 'failed'             – at least one step failed (execution stopped)
    - 'approval_required'  – paused waiting for user approval
    - 'running'            – in progress (streaming / async future use)
    """

    message: Optional[str] = None
    """Human-readable summary of the outcome."""

    tts_text: Optional[str] = None
    """TTS-optimised short version of the outcome (localised to assistant_language)."""

    memory_hints: List[str] = Field(default_factory=list)
    """Short notes about which memory defaults were applied, shown in the chat UI."""
