"""
episodic_memory.py – ORM model for Lani's autobiographical memory.

Every event (conversation turn, tool execution, important observation)
is logged here automatically. Lani can query this to answer:
  "What did I do today?"
  "When did the user last ask about X?"
  "What files have I created this week?"

This is distinct from the structured MemoryEntry table (which stores
user-declared facts). Episodic memory is automatic and time-ordered.
"""

import datetime
from sqlalchemy import Integer, String, Text, DateTime, Float, Index
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base


class EpisodicEvent(Base):
    """
    A single autobiographical event in Lani's memory.

    event_type:
      conversation  – chat turn (user+assistant)
      tool_call     – a tool was executed
      observation   – Lani noticed something (error, file created, etc.)
      reflection    – Lani's self-reflection (generated by reflection service)
    """

    __tablename__ = "episodic_memory"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    event_type: Mapped[str] = mapped_column(String(40), nullable=False, default="conversation")
    """conversation | tool_call | observation | reflection"""

    session_id: Mapped[str] = mapped_column(String(80), nullable=False, default="default")

    # For conversation events
    user_message: Mapped[str] = mapped_column(Text, nullable=False, default="")
    assistant_response: Mapped[str] = mapped_column(Text, nullable=False, default="")

    # For tool_call events
    tool_name: Mapped[str] = mapped_column(String(80), nullable=False, default="")
    tool_args: Mapped[str] = mapped_column(Text, nullable=False, default="")   # JSON
    tool_result: Mapped[str] = mapped_column(Text, nullable=False, default="")
    tool_success: Mapped[bool] = mapped_column(nullable=False, default=True)

    # For reflection events
    reflection_text: Mapped[str] = mapped_column(Text, nullable=False, default="")

    # Semantic embedding for search (JSON float array)
    embedding: Mapped[str] = mapped_column(Text, nullable=True)

    # Importance score 0.0-1.0 (higher = keep longer / surface first)
    importance: Mapped[float] = mapped_column(Float, nullable=False, default=0.5)

    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime, default=datetime.datetime.utcnow, nullable=False
    )

    __table_args__ = (
        Index("ix_episodic_type_created", "event_type", "created_at"),
        Index("ix_episodic_session", "session_id", "created_at"),
        Index("ix_episodic_tool", "tool_name", "created_at"),
    )
