"""
Presentation generation tool using python-pptx.

Creates a simple PowerPoint file with a title slide followed by one
content slide per outline item.
"""

from pathlib import Path
from typing import Any, Dict, List

from app.schemas.commands import ToolResult
from app.tools.base import BaseTool
from app.tools.file_tools import _allowed, _deny


class CreatePresentationTool(BaseTool):
    name = "create_presentation"
    description = (
        "Generate a PowerPoint presentation (.pptx) from a title and outline. "
        "Saves to Desktop by default."
    )
    requires_approval = False
    parameters = [
        {"name": "title", "description": "Title of the presentation", "required": True},
        {"name": "outline", "description": "List of slide topics/sections, e.g. ['Introduction', 'Goals', 'Results']", "required": True},
        {"name": "output_path", "description": "Where to save the .pptx file. Defaults to ~/Desktop/<title>.pptx", "required": False},
    ]

    async def run(self, params: Dict[str, Any]) -> ToolResult:
        title: str = params.get("title", "Presentation")
        outline: List[str] = params.get("outline", [])
        # Default output path to Desktop if not provided
        output_path: str = params.get("output_path") or f"~/Desktop/{title}.pptx"
        output_path = str(Path(output_path).expanduser())

        if not _allowed(output_path):
            return _deny(output_path)

        try:
            from pptx import Presentation  # type: ignore
            from pptx.util import Inches, Pt  # type: ignore
        except ImportError:
            return ToolResult(
                tool_name=self.name,
                status="error",
                message="python-pptx is not installed. Run: pip install python-pptx",
            )

        try:
            prs = Presentation()

            # --- Title slide ---
            title_slide_layout = prs.slide_layouts[0]
            slide = prs.slides.add_slide(title_slide_layout)
            slide.shapes.title.text = title
            if slide.placeholders[1]:
                slide.placeholders[1].text = "Generated by Lani"

            # --- Content slides (one per outline item) ---
            bullet_layout = prs.slide_layouts[1]
            for idx, item in enumerate(outline, start=1):
                slide = prs.slides.add_slide(bullet_layout)
                slide.shapes.title.text = f"{idx}. {item}"
                # Leave body placeholder empty – user can fill in details
                if len(slide.placeholders) > 1:
                    slide.placeholders[1].text = ""

            Path(output_path).parent.mkdir(parents=True, exist_ok=True)
            prs.save(output_path)

            return ToolResult(
                tool_name=self.name,
                status="success",
                message=f"Presentation saved to '{output_path}' ({len(outline)} slide(s)).",
                data={
                    "output_path": output_path,
                    "title": title,
                    "slide_count": len(outline) + 1,
                },
            )
        except Exception as exc:
            return ToolResult(tool_name=self.name, status="error", message=str(exc))
