"""
episodic_memory_service.py – Lani's autobiographical memory engine.

Automatically logs every event. Lani can recall:
  • What she did today / this week
  • Full conversation history with semantic search
  • Which tools she used and what happened
  • Her own reflections and observations

Public API
──────────
  log_conversation(session_id, user_msg, assistant_msg)
  log_tool_call(session_id, tool_name, args, result, success)
  log_observation(session_id, text, importance)
  log_reflection(session_id, text)
  recall(query, limit, days_back, event_type)  → list[EpisodicEvent]
  recall_today(session_id)                     → str (formatted summary)
  recall_week_summary()                        → str
"""

from __future__ import annotations

import json
import logging
import math
from datetime import datetime, timedelta, timezone
from typing import List, Optional

from sqlalchemy import select, and_, desc
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import AsyncSessionLocal
from app.models.episodic_memory import EpisodicEvent

log = logging.getLogger(__name__)


def _utcnow() -> datetime:
    """Return a timezone-aware UTC timestamp."""
    return datetime.now(timezone.utc)

_MAX_KEEP_DAYS = 90   # auto-prune events older than this
_EMBED_EVENTS = {"conversation", "reflection", "observation"}  # embed these for semantic search


# ─── Writers ──────────────────────────────────────────────────────────────────

async def log_conversation(
    session_id: str,
    user_msg: str,
    assistant_msg: str,
    importance: float = 0.5,
) -> None:
    """Log a conversation turn. Called automatically by chat_tool."""
    embedding = await _embed(f"{user_msg} {assistant_msg}")
    async with AsyncSessionLocal() as db:
        db.add(EpisodicEvent(
            event_type="conversation",
            session_id=session_id,
            user_message=user_msg[:2000],
            assistant_response=assistant_msg[:4000],
            importance=importance,
            embedding=json.dumps(embedding) if embedding else None,
        ))
        await db.commit()


async def log_tool_call(
    session_id: str,
    tool_name: str,
    args: dict,
    result: str,
    success: bool = True,
    importance: float = 0.4,
) -> None:
    """Log a tool execution. Called automatically by plan_executor."""
    async with AsyncSessionLocal() as db:
        db.add(EpisodicEvent(
            event_type="tool_call",
            session_id=session_id,
            tool_name=tool_name,
            tool_args=json.dumps(args, ensure_ascii=False)[:1000],
            tool_result=result[:2000],
            tool_success=success,
            importance=importance,
        ))
        await db.commit()


async def log_observation(
    session_id: str,
    text: str,
    importance: float = 0.6,
) -> None:
    """Log an important observation (error, milestone, etc.)."""
    embedding = await _embed(text)
    async with AsyncSessionLocal() as db:
        db.add(EpisodicEvent(
            event_type="observation",
            session_id=session_id,
            assistant_response=text[:4000],
            importance=importance,
            embedding=json.dumps(embedding) if embedding else None,
        ))
        await db.commit()


async def log_reflection(
    session_id: str,
    text: str,
    importance: float = 0.8,
) -> None:
    """Log a self-reflection (generated by reflection service)."""
    embedding = await _embed(text)
    async with AsyncSessionLocal() as db:
        db.add(EpisodicEvent(
            event_type="reflection",
            session_id=session_id,
            reflection_text=text[:4000],
            importance=importance,
            embedding=json.dumps(embedding) if embedding else None,
        ))
        await db.commit()


# ─── Recall ───────────────────────────────────────────────────────────────────

async def recall(
    query: str,
    limit: int = 10,
    days_back: int = 30,
    event_type: Optional[str] = None,
    session_id: Optional[str] = None,
) -> List[EpisodicEvent]:
    """
    Semantic + recency search over episodic memory.
    Returns up to `limit` most relevant events.
    """
    query_embedding = await _embed(query)
    since = _utcnow() - timedelta(days=days_back)

    async with AsyncSessionLocal() as db:
        stmt = select(EpisodicEvent).where(EpisodicEvent.created_at >= since)
        if event_type:
            stmt = stmt.where(EpisodicEvent.event_type == event_type)
        if session_id:
            stmt = stmt.where(EpisodicEvent.session_id == session_id)
        stmt = stmt.order_by(desc(EpisodicEvent.created_at)).limit(200)
        result = await db.execute(stmt)
        events = list(result.scalars().all())

    if query_embedding:
        # Rank by cosine similarity + recency + importance
        scored = []
        for ev in events:
            sim = 0.5
            if ev.embedding:
                try:
                    ev_vec = json.loads(ev.embedding)
                    sim = _cosine(query_embedding, ev_vec)
                except Exception:
                    pass
            # Blend: 60% semantic, 20% importance, 20% recency (decays over days_back)
            age_days = (_utcnow() - ev.created_at).total_seconds() / 86400
            recency = max(0.0, 1.0 - age_days / days_back)
            score = 0.60 * sim + 0.20 * ev.importance + 0.20 * recency
            scored.append((score, ev))
        scored.sort(key=lambda x: x[0], reverse=True)
        events = [ev for _, ev in scored[:limit]]
    else:
        events = events[:limit]

    return events


async def recall_today(session_id: str = "default") -> str:
    """Return a human-readable summary of today's activity."""
    since = _utcnow() - timedelta(hours=24)
    async with AsyncSessionLocal() as db:
        stmt = (
            select(EpisodicEvent)
            .where(
                and_(
                    EpisodicEvent.session_id == session_id,
                    EpisodicEvent.created_at >= since,
                )
            )
            .order_by(EpisodicEvent.created_at)
        )
        result = await db.execute(stmt)
        events = list(result.scalars().all())

    if not events:
        return "Šiandien dar nebuvo jokios veiklos."

    lines = [f"📅 Veikla per paskutines 24 val. ({len(events)} įvykių):"]
    for ev in events[-30:]:  # show last 30
        ts = ev.created_at.strftime("%H:%M")
        if ev.event_type == "conversation":
            lines.append(f"  {ts} 💬 {ev.user_message[:80]}")
        elif ev.event_type == "tool_call":
            status = "✅" if ev.tool_success else "❌"
            lines.append(f"  {ts} {status} [{ev.tool_name}] {ev.tool_result[:60]}")
        elif ev.event_type == "reflection":
            lines.append(f"  {ts} 🧠 {ev.reflection_text[:80]}")
        elif ev.event_type == "observation":
            lines.append(f"  {ts} 👁 {ev.assistant_response[:80]}")
    return "\n".join(lines)


async def recall_week_summary() -> str:
    """Return a brief summary of this week's activity stats."""
    since = _utcnow() - timedelta(days=7)
    async with AsyncSessionLocal() as db:
        stmt = select(EpisodicEvent).where(EpisodicEvent.created_at >= since)
        result = await db.execute(stmt)
        events = list(result.scalars().all())

    if not events:
        return "Šią savaitę jokios veiklos nebuvo."

    convs = sum(1 for e in events if e.event_type == "conversation")
    tools = sum(1 for e in events if e.event_type == "tool_call")
    tools_ok = sum(1 for e in events if e.event_type == "tool_call" and e.tool_success)
    tool_names = [e.tool_name for e in events if e.event_type == "tool_call" and e.tool_name]
    from collections import Counter
    top_tools = Counter(tool_names).most_common(5)
    reflections = sum(1 for e in events if e.event_type == "reflection")

    lines = [
        f"📊 Savaitės apžvalga ({len(events)} įvykių):",
        f"  💬 Pokalbiai: {convs}",
        f"  🔧 Įrankiai: {tools} (sėkmingų: {tools_ok})",
        f"  🧠 Refleksijos: {reflections}",
    ]
    if top_tools:
        top_str = ", ".join(f"{n}({c})" for n, c in top_tools)
        lines.append(f"  🏆 Dažniausi įrankiai: {top_str}")
    return "\n".join(lines)


# ─── Maintenance ──────────────────────────────────────────────────────────────

async def prune_old_events(days: int = _MAX_KEEP_DAYS) -> int:
    """Delete low-importance events older than `days` days. Returns deleted count."""
    from sqlalchemy import delete
    cutoff = _utcnow() - timedelta(days=days)
    async with AsyncSessionLocal() as db:
        result = await db.execute(
            delete(EpisodicEvent).where(
                and_(
                    EpisodicEvent.created_at < cutoff,
                    EpisodicEvent.importance < 0.7,  # keep high-importance forever
                )
            )
        )
        await db.commit()
        deleted = result.rowcount
    log.info("[episodic] pruned %d old events (older than %d days)", deleted, days)
    return deleted


# ─── Helpers ──────────────────────────────────────────────────────────────────

async def _embed(text: str) -> Optional[list]:
    """Get embedding vector for text. Returns None if OpenAI not configured."""
    try:
        from app.core.config import settings as cfg
        api_key = getattr(cfg, "OPENAI_API_KEY", "") or ""
        if not api_key:
            return None
        import openai
        client = openai.AsyncOpenAI(api_key=api_key)
        model = getattr(cfg, "EMBEDDING_MODEL", "text-embedding-3-large")
        resp = await client.embeddings.create(model=model, input=text[:8000])
        return resp.data[0].embedding
    except Exception as exc:
        log.debug("[episodic] embed failed: %s", exc)
        return None


def _cosine(a: list, b: list) -> float:
    if len(a) != len(b):
        return 0.0
    dot = sum(x * y for x, y in zip(a, b))
    na = math.sqrt(sum(x * x for x in a))
    nb = math.sqrt(sum(x * x for x in b))
    if na == 0 or nb == 0:
        return 0.0
    return dot / (na * nb)
